# Generated by Django 4.2.19 on 2025-03-30 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_menuitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting for Confirmation'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='waiting', max_length=10),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('appetizer', 'Appetizer & Salads'), ('main_course', 'Main Course'), ('dessert', 'Dessert'), ('beverage', 'Beverage')], default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='guests',
            field=models.IntegerField(default=1),
        ),
    ]
