# Generated by Django 4.2.19 on 2025-03-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_menuitem_available_menuitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting for Confirmation'), ('confirmed', 'Confirmed'), ('canceled', 'Canceled')], default='waiting', max_length=10),
        ),
    ]
