# Generated by Django 4.2.19 on 2025-03-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting for Confirmation'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='waiting', max_length=10),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('appetizer', 'Appetizer & Salads'), ('main_course', 'Main Course'), ('dessert', 'Dessert'), ('beverage', 'Beverage')], max_length=20),
        ),
    ]
